version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: k8s.io/*
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
- package-ecosystem: gomod
  directory: "/hack/controller-gen"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/hack/ginkgo"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/hack/kustomize"
  schedule:
    interval: daily
