
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - service.binding
  resources:
  - clusterapplicationresourcemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.binding
  resources:
  - clusterapplicationresourcemappings/finalizers
  verbs:
  - update
- apiGroups:
  - service.binding
  resources:
  - clusterapplicationresourcemappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - service.binding
  resources:
  - servicebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.binding
  resources:
  - servicebindings/finalizers
  verbs:
  - update
- apiGroups:
  - service.binding
  resources:
  - servicebindings/status
  verbs:
  - get
  - patch
  - update
